#!/usr/bin/env bash
# A script that will display information about subdomains.

# Function to display information about a subdomain
display_subdomain_info() {
    result=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $result" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]; then
    display_subdomain_info "$1" "www"
    display_subdomain_info "$1" "lb-01"
    display_subdomain_info "$1" "web-01"
    display_subdomain_info "$1" "web-02"
elif [ "$#" == 2 ]; then
    display_subdomain_info "$1" "$2"
fi
