#!/usr/bin/env bash
# A script that will display information about subdomains.

domain="$1"; subdomain="$2";
subs=("www" "lb-01" "web-01" "web-02")

# Display information about a subdomain
display_subdomain_info () {
    echo -e "The subdomain $1 is a $2 record and points to $3"
}

# Get information on top level domains
get_domain_info () {
    top_level_domain="$1"; sub_domain="$2";
    result=$(dig "${top_level_domain}" | grep -A1 'ANSWER SECTION:' | awk 'NR>1');
    record_type=$(echo "${result}" | awk '{print $4}');
    destination=$(echo "${result}" | awk '{print $5}');
    display_subdomain_info "$sub_domain" "$record_type" "$destination";
}

# Get information on sub-domains
get_subdomains () {
    for sub in "${subs[@]}"; do
        get_domain_info "${sub}.${domain}" "${sub}";
    done
}

if [ "$#" -eq 1 ]; then
    get_subdomains
    exit 0;
fi

get_domain_info "${subdomain}.${domain}" "${subdomain}";
