#!/usr/bin/env bash
# Nginx server config to have a custom 404 page.

# Update package list and install Nginx
sudo apt-get -y update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www

echo 'Hello World!' > /var/www/html/index.html

configuration=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
}"

# Insert the custom 404 location data into the Nginx configuration file
bash -c "echo -e '$configuration' > /etc/nginx/sites-enabled/default"

# Restart Nginx service to apply changes
if [ "$(pgrep -c nginx)" -le 0 ]; then
	sudo service nginx start
else
	sudo service nginx restart
fi
