#!/usr/bin/env bash
# Nginx server config to redirect /redirect_me to another page.

# Update package list and install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

# Create a default HTML page
default_page="/var/www/html/index.html"
echo "Hello World!" | sudo tee "$default_page"

# Use double quotes for variable expansion in sed
sed -i "37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

# Start Nginx service
sudo service nginx start
