#!/usr/bin/env bash
# Nginx server config to redirect /redirect_me to another page.

# Update package list and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Set file permissions for the web server directories
sudo chown -R "$USER":"$USER" /var/www/html/
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/

# Create a default HTML page
echo 'Hello World!' > /var/www/html/index.html

# Define the redirection location data
redirect="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

# Insert the redirection location data into the Nginx configuration file
sudo sed -i "26i $redirect" /etc/nginx/sites-available/default

# Start or Reload Nginx service
if [[ $(pgrep nginx) ]]; then
    sudo nginx -s reload
else
    sudo service nginx start
fi
