#!/usr/bin/env bash
# Nginx server config to have a custom 404 page.

# Update package list and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Default index.html page
echo 'Hello World' > /var/www/html/index.html

# Configure the web server
ufw allow 'Nginx HTTP'

configuration_file="/etc/nginx/sites-available/default"

# Add redirection
new_site="https://www.youtube.com/watch?v=QH2-TGUlwu4"

sed -i "/listen 80 default_server/a rewrite ^/redirect_me $new_site permanent;" $configuration_file

# Create a default 404 HTML page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Insert the custom 404 location data into the Nginx configuration file
the_404_page="404.html"
link_to_404_file="/404.html {root /usr/share/nginx/html;\n internal;}"
sed -i "/listen 80 default_server/a error_page 404 /$the_404_page; location = $link_to_404_file" $configuration_file

# Restart Nginx service to apply changes
sudo service nginx start
