#!/usr/bin/env bash
# Nginx server config to have a custom 404 page.

# Update package list and install Nginx
sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
chmod -R 755 /var/www


echo 'Hello World' > /var/www/html/index.html

configuration=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
               root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files \$uri \$uri/ =404;
        }
        error_page 404 /404.html;
        location  /404.html {
            internal;
        }
        
        if (\$request_filename ~ redirect_me){
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
}
"

# Create a default 404 HTML page
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Insert the custom 404 location data into the Nginx configuration file
echo "$configuration" > /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
if [ "$(pgrep nginx)" -le 0 ];
then
    service nginx start
else
    service nginx restart
fi;
