#!/usr/bin/env bash
# A script that fixes a Nginx web server
# Update the Nginx configuration file to listen on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
