#!/usr/bin/env bash
# A script that fixes a Nginx web server

# Update the Nginx configuration file to listen on port 80
sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
service nginx restart
