#!/usr/bin/env bash

PID_FILE="myscript"
PID_DIR="/var/run"

SIGINT_MESSAGE () {
	echo -e "Y U no love me?!"
}

QUIT_MESSAGE () {
	rm -rf "${PID_DIR}/${PID_FILE}.pid"
	echo -e "I hate the kill command"
	exit 0
}

trap "SIGINT_MESSAGE" SIGINT
trap "QUIT_MESSAGE" SIGTERM
trap "QUIT_MESSAGE" SIGQUIT


# Create the file
echo $$ >> "${PID_DIR}/${PID_FILE}.pid"

while true; do
	echo -e "To infinity and beyond"
	sleep 2
done
