#!/usr/bin/env bash

SCRIPT_PATH="$(dirname "$(readlink -f "$0")")"
PID_FILE="/var/run/my_process.pid"

case $1 in
    start)
        if [ -f "$PID_FILE" ]; then
            echo "manage_my_process is already running."
        else
            $SCRIPT_PATH/manage_my_process &
            echo $! > "$PID_FILE"
            echo "manage_my_process started"
        fi
        ;;
    stop)
        if [ -f "$PID_FILE" ]; then
            PID=$(cat "$PID_FILE")
            kill "$PID" && wait "$PID" 2>/dev/null
            rm "$PID_FILE"
            echo "manage_my_process stopped"
        else
            echo "manage_my_process is not running."
        fi
        ;;
    restart)
        $0 stop
        $0 start
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
