#!/usr/bin/env bash
# Find the process ID (PID) of the 4-to_infinity_and_beyond script
# Check if the process is running
# Use pkill to send a termination signal to the process

pkill -f 4-to_infinity_and_beyond
