#!/usr/bin/env bash
# This script displays specific information from /etc/passwd

while IFS=":" read -r username x userid groupid gecos homedir shell; do
  echo "$username:$userid:$homedir"
done </etc/passwd
