#!/usr/bin/env bash
# This script tells a fictional story based on the /etc/passwd file

while IFS=":" read -r username _ userid groupid gecos homedir shell; do
  echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $gecos"
done </etc/passwd
