#!/usr/bin/env bash
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8


HOST_FILE="/etc/hosts"
HOST_COPY="temp_host"
HOST_BAK="bak_host"
WILD_CARD="127*.*localhost"
LOCAL_HOST="	127.0.0.2	localhost"
FACEBOOK="	8.8.8.8		facebook.com"

cp "${HOST_FILE}" "${HOST_COPY}"
cp "${HOST_FILE}" "${HOST_BAK}"

DONE=0

cat -n "${HOST_FILE}" | grep "${WILD_CARD}" | sed 's/  \+ //' | cut -c 1-1 |
while read -r i; do
	sed -i "$((i+DONE))d" ${HOST_COPY}
	sed -i "$((i+DONE))i ${LOCAL_HOST}" "${HOST_COPY}"

	[[ $DONE -eq 0 ]] && sed -i "$((i+1))i ${FACEBOOK}" "${HOST_COPY}"
	DONE=1
done

cp -f "${HOST_COPY}" "${HOST_FILE}"
